### ISSUE TITLE
Cutscene Audio Changing At Wrong Time in Endwalker

### ISSUE THREAD

**Issue by moorecp** [Judisch/FastPraetorium#2]
I haven't tracked down where, yet, but when I enter the final story dungeon of EW via Expert Roulette, I notice my cutscene audio has changed to Japanese. I'm not sure when it's changing, yet, but something sure is causing it to change outside of Praetorium as I haven't been in there since adding this plugin and it's happened to me twice.

I'll post more if I notice when it's changing; just a heads up until then or if other people notice.

**Comment by anna-is-cute** [comment]
This happens in multiple places. The target changed function should be checking that the player is in Praetorium, I think.

**Comment by Judisch** [comment]
Since The Praetorium is being removed in patch 6.1 (April 12th), this plugin isn't useful anymore. Sorry for the inconvenience of getting your language changed
